spring.application.name=user-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/BMS_Users_DB
spring.datasource.username=postgres
spring.datasource.password=5432

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.private-key=classpath:keys/private-key.pem
jwt.public-key=classpath:keys/public-key.pem